apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  app.successfactors.com/env-type: sales
  app.successfactors.com/datacenter: dc2
resources:
  - ingress.yaml
  - https://github.com/raviusit/hello-kubernetes-dev-config/base/?ref=v1.0
patchesStrategicMerge:
  - custom-env.yaml
